from kivy.app import App
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.gridlayout import GridLayout
from kivy.uix.image import Image
from kivy.uix.textinput import TextInput
from kivy.uix.boxlayout import BoxLayout  # Add this line to import BoxLayout

Alabama = "Alabama Sturgeon (Scaphirhynchus suttkusi): The Alabama sturgeon is a critically endangered freshwater fish found in the Mobile River Basin. \n  It is one of the rarest sturgeon species globally and faces threats such as habitat alteration, river channelization, and navigation infrastructure. \n  Watercress Darter (Etheostoma nuchale): The watercress darter is a small, colorful fish found in the Black Warrior River Basin in Alabama. \n  Habitat destruction, pollution, and water quality degradation have led to its endangered status. \n  \n  Cahaba Shiner (Notropis cahabae): The Cahaba shiner is a small, silvery fish native to the Cahaba River and its tributaries. \n  It is listed as endangered due to habitat loss, water pollution, and competition with non-native species. \n  Vermilion Darter (Etheostoma chermocki): The vermilion darter is a colorful fish species found in the Turkey Creek system in Alabama. \n  Urban development and water quality issues have contributed to its endangered status. \n  Gulf Sturgeon (Acipenser oxyrinchus desotoi): Gulf sturgeon are anadromous fish that inhabit Gulf of Mexico coastal rivers, including some in Alabama. \n  They are listed as threatened due to factors such as habitat degradation and waterway development. \n  Eastern Indigo Snake (Drymarchon couperi): While not an aquatic species, the Eastern indigo snake is often associated with wetland and aquatic habitats. \n  It is listed as threatened due to habitat loss and fragmentation. \n  Southern Clubshell (Pleurobema decisum): The southern clubshell is a freshwater mussel species found in several rivers in Alabama. \n  It is listed as threatened due to habitat destruction, water pollution, and sedimentation. \n ."
Alaska = "Cook Inlet Beluga Whale (Delphinapterus leucas): The Cook Inlet beluga whale, a distinct population of beluga whales found in Cook Inlet, Alaska, is listed as endangered. \n  Population decline has been attributed to various factors, including habitat degradation, pollution, and reduced prey availability. \n  Steller Sea Lion (Eumetopias jubatus): While primarily a marine mammal, Steller sea lions inhabit coastal areas and haul-out sites in Alaska. \n  They are listed as endangered in the western population, which includes parts of Alaska, due to declining numbers. \n  Spectacled Eider (Somateria fischeri): The spectacled eider is a sea duck that nests in Arctic Alaska. \n  It is listed as endangered due to habitat alteration, oil development, and climate change impacts on its breeding grounds. \n  Short-tailed Albatross (Phoebastria albatrus): Although primarily a marine bird, short-tailed albatrosses are listed as endangered. \n  They nest on remote islands in the North Pacific, including Alaskan islands. \n  Historic exploitation and habitat destruction have contributed to their endangered status. \n  Northern Sea Otter (Enhydra lutris kenyoni): The northern sea otter, found along Alaska's coast, is listed as threatened in parts of its range. \n  Threats include oil pollution, predation by orcas, and habitat alteration. \n  Steelhead Trout (Oncorhynchus mykiss): Steelhead trout populations in Alaska are listed as threatened in some areas. \n  Threats include habitat degradation, overfishing, and climate change. \n  Humpback Whale (Megaptera novaeangliae): While primarily a marine species, humpback whales are listed as threatened in some of their Alaskan habitats. \n  They face threats from entanglement in fishing gear and vessel strikes. \n "
Arizona = "Gila Topminnow (Poeciliopsis occidentalis): The Gila topminnow is a small native fish species found in Arizona's desert streams. \n  It is listed as endangered due to habitat loss and competition with non-native species. \n  Razorback Sucker (Xyrauchen texanus): The razorback sucker is a large, long-lived fish native to the Colorado River Basin. \n  It is listed as endangered due to habitat alteration, dam construction, and non-native species. \n  Colorado Pikeminnow (Ptychocheilus lucius): Colorado pikeminnow, also known as Colorado squawfish, is another large native fish species found in the Colorado River Basin. \n  It is listed as endangered for similar reasons as the razorback sucker. \n  Southwestern Willow Flycatcher (Empidonax traillii extimus): While primarily a bird species, the southwestern willow flycatcher nests in riparian habitats in Arizona. \n  It is listed as threatened due to habitat loss and degradation. \n  Bald Eagle (Haliaeetus leucocephalus): Bald eagles are known for their association with aquatic habitats and are listed as threatened in Arizona due to habitat loss and disturbances around nesting sites. \n  Yellow-billed Cuckoo (Coccyzus americanus): Yellow-billed cuckoos are riparian bird species and are listed as threatened due to habitat loss and degradation of riparian areas. \n "
Arkansas = "Ozark Hellbender (Cryptobranchus alleganiensis bishopi): The Ozark hellbender is a large, aquatic salamander that inhabits clear, fast-flowing streams in the Ozark Highlands of Arkansas and Missouri. \n  It is listed as endangered due to habitat degradation, water pollution, and disease. \n  Arkansas Fatmucket Mussel (Lampsilis powellii): The Arkansas fatmucket is an endangered freshwater mussel species found in Arkansas rivers. \n  Habitat destruction and water pollution are the primary threats to its survival. \n  Ivory Heelsplitter Mussel (Lasmigona costata): The ivory heelsplitter is a threatened freshwater mussel species that occurs in various water bodies in Arkansas. \n  It is threatened by habitat alteration, water pollution, and competition with invasive species. \n  Northern Long-eared Bat (Myotis septentrionalis): While primarily a terrestrial species, the northern long-eared bat hibernates in caves and roosts in forested areas near aquatic habitats. \n  It is listed as threatened due to white-nose syndrome, a fungal disease that affects bats in caves. \n  Louisiana Black Bear (Ursus americanus luteolus): The Louisiana black bear, which includes populations in the Mississippi Alluvial Valley of Arkansas, is listed as threatened. \n  Wetlands and riparian areas are important habitats for this bear species. \n "
California = "Southern Steelhead Trout (Oncorhynchus mykiss): Southern steelhead trout is an anadromous fish species found in California's coastal rivers and streams. \n  It is listed as endangered due to habitat loss, water diversions, and other threats. \n  California Red-legged Frog (Rana draytonii): The California red-legged frog is an amphibian species found in aquatic habitats. \n  It is listed as endangered due to habitat loss, non-native predators, and disease. \n  Coho Salmon (Oncorhynchus kisutch): Coho salmon populations in California are listed as endangered or threatened in some regions due to habitat degradation, water diversions, and overfishing. \n  California Tiger Salamander (Ambystoma californiense): The California tiger salamander inhabits seasonal wetlands and relies on aquatic habitats for breeding. \n  It is listed as endangered due to habitat loss and fragmentation. \n  Delta Smelt (Hypomesus transpacificus): Delta smelt is a small fish species found in the Sacramento-San Joaquin Delta. \n  It is highly endangered due to water management practices, habitat alteration, and competition with non-native species. \n  Green Sea Turtle (Chelonia mydas): Green sea turtles are primarily marine, but they are listed as threatened in California due to their use of coastal habitats and the potential for bycatch in fishing gear. \n  Olive Ridley Sea Turtle (Lepidochelys olivacea): Olive Ridley sea turtles are also primarily marine but are listed as threatened in California for similar reasons as the green sea turtle. \n  San Francisco Garter Snake (Thamnophis sirtalis tetrataenia): While primarily terrestrial, the San Francisco garter snake is associated with aquatic habitats and is listed as threatened due to habitat loss and non-native species. \n  California Least Tern (Sternula antillarum browni): The California least tern nests in coastal areas near aquatic habitats and is listed as threatened due to habitat loss and disturbance. \n "
Colorado = "Greenback Cutthroat Trout (Oncorhynchus clarkii stomias): The greenback cutthroat trout is Colorado's state fish and is listed as endangered. \n  It was once thought to be extinct but has been rediscovered in a few isolated populations. \n  Habitat loss, competition with non-native trout species, and hybridization are among the threats it faces. \n  Bonytail Chub (Gila elegans): The bonytail chub is a critically endangered fish native to the Colorado River Basin, including Colorado. \n  Dams, water diversions, and habitat alterations have contributed to its decline. \n  Humpback Chub (Gila cypha): Humpback chub is another endangered fish species found in the Colorado River Basin, including Colorado. \n  It faces similar threats as the bonytail chub. \n  Colorado Pikeminnow (Ptychocheilus lucius): The Colorado pikeminnow, also known as the Colorado squawfish, is a large fish species found in the Colorado River Basin, including Colorado. \n  It is listed as endangered due to habitat degradation and the construction of dams. \n  Razorback Sucker (Xyrauchen texanus): Razorback suckers are endangered fish species found in the Colorado River Basin, including Colorado. \n  They are threatened by habitat alteration, non-native species, and competition with other fish. \n  Mexican Spotted Owl (Strix occidentalis lucida): While primarily a terrestrial bird, the Mexican spotted owl inhabits riparian areas and is considered threatened in Colorado due to habitat loss and degradation. \n  Western Yellow-billed Cuckoo (Coccyzus americanus occidentalis): The western yellow-billed cuckoo is a riparian bird species listed as threatened due to habitat loss and degradation in Colorado. \n "
Connecticut = "Connecticut is a state with a variety of aquatic ecosystems, including rivers, lakes, ponds, and coastal areas, which support a range of aquatic species. \n There are no government recognized endangered aquatic species. \n"
Delaware = "Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon is a large, long-lived fish species found in the Delaware River and Delaware Bay. \n  It is listed as endangered due to historical overfishing, habitat degradation, and barriers to migration. \n  Red Knot (Calidris canutus): The red knot is a migratory shorebird that relies on Delaware Bay's horseshoe crab eggs during migration. \n  Overharvesting of horseshoe crabs for bait has led to a decline in red knot populations, leading to its endangered status. \n  Shortnose Sturgeon (Acipenser brevirostrum): Similar to Atlantic sturgeon, the shortnose sturgeon is listed as threatened in Delaware due to habitat degradation, overfishing, and barriers to migration. \n  Piping Plover (Charadrius melodus): While primarily a beach-nesting bird, the piping plover depends on coastal habitats, including tidal flats and estuaries. \n  It is listed as threatened in Delaware due to habitat loss and disturbance. \n  American Eel (Anguilla rostrata): American eels are found in various aquatic habitats, including rivers and streams in Delaware. \n  They are listed as threatened due to habitat alterations such as dams and barriers that impede their migration. \n "
Florida = "Florida Manatee (Trichechus manatus latirostris): The Florida manatee, a subspecies of the West Indian manatee, is listed as endangered. \n  Manatees inhabit Florida's waterways, including rivers, springs, and coastal areas. \n  They face threats from boat strikes, habitat loss, and cold stress. \n  Florida Panther (Puma concolor coryi): The Florida panther is a terrestrial mammal, but it relies on aquatic habitats for drinking and is considered endangered. \n  Wetland habitat preservation is crucial for the panther's survival. \n  American Crocodile (Crocodylus acutus): The American crocodile is found in Florida's coastal areas, including the Everglades. \n  It is listed as endangered due to habitat loss and human activities. \n  West Indian Manatee (Trichechus manatus): In addition to the Florida manatee, the West Indian manatee includes individuals found in Florida and is listed as endangered for similar reasons. \n  Eastern Indigo Snake (Drymarchon couperi): While primarily a terrestrial species, the eastern indigo snake inhabits areas near rivers and streams in Florida. \n  It is listed as threatened due to habitat loss and fragmentation. \n  Loggerhead Sea Turtle (Caretta caretta): Loggerhead sea turtles nest on Florida's beaches and are listed as threatened. \n  They face threats such as habitat degradation, artificial lighting, and fishing bycatch. \n  Kemp's Ridley Sea Turtle (Lepidochelys kempii): Kemp's ridley sea turtles are primarily found in the Gulf of Mexico, including Florida waters. \n  They are listed as threatened due to habitat degradation, incidental capture, and marine pollution. \n  Green Sea Turtle (Chelonia mydas): Green sea turtles are found in Florida's coastal waters and are listed as threatened due to threats such as habitat degradation and entanglement in fishing gear. \n  Florida Scrub-Jay (Aphelocoma coerulescens): While a terrestrial bird, the Florida scrub-jay inhabits scrub habitats near wetlands and rivers. \n  It is listed as threatened due to habitat loss and fragmentation. \n "
Georgia = "Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon, a large and long-lived fish species, can be found in the coastal waters and rivers of Georgia. \n  It is listed as endangered due to overfishing, habitat degradation, and barriers to migration. \n  Shortnose Sturgeon (Acipenser brevirostrum): Similar to the Atlantic sturgeon, the shortnose sturgeon is listed as endangered in Georgia for similar reasons—habitat degradation, overfishing, and migration barriers. \n  Southern Pigtoe Mussel (Pleurobema georgianum): The southern pigtoe mussel is a freshwater mussel native to Georgia rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and competition with invasive species. \n  Oval Pigtoe Mussel (Pleurobema pyriforme): The oval pigtoe mussel is another endangered freshwater mussel species found in Georgia's river systems. \n  It faces similar threats to the southern pigtoe mussel. \n  Alabama Map Turtle (Graptemys pulchra): The Alabama map turtle is found in Georgia's rivers and is listed as threatened. \n  Habitat alteration and pollution are threats to this species. \n  Etowah Darter (Etheostoma etowahae): The Etowah darter is a small fish native to the Etowah River system in Georgia. \n  It is listed as threatened due to habitat loss and water quality issues. \n  Robust Redhorse (Moxostoma robustum): The robust redhorse is a large, long-lived fish found in Georgia rivers. \n  It is listed as threatened due to habitat degradation and barriers to migration. \n "
Hawaii = "Hawaiian Monk Seal (Neomonachus schauinslandi): The Hawaiian monk seal is a marine mammal native to the Hawaiian Islands. \n  It is listed as endangered due to factors such as habitat loss, entanglement in marine debris, and interactions with fisheries. \n  Hawksbill Sea Turtle (Eretmochelys imbricata): Hawksbill sea turtles are found in Hawaii's coastal waters and are listed as endangered. \n  Threats include habitat degradation, accidental capture in fishing gear, and the illegal trade in hawksbill products. \n  Leatherback Sea Turtle (Dermochelys coriacea): Leatherback sea turtles occasionally visit Hawaiian waters and are listed as endangered. \n  They face threats such as bycatch in fishing gear and ingestion of marine debris. \n  Green Sea Turtle (Chelonia mydas): Green sea turtles are commonly found in Hawaiian waters and are listed as threatened. \n  Conservation efforts have helped their populations recover, but they still face threats such as habitat degradation and bycatch. \n  Hawaiian Hoary Bat (Lasiurus cinereus semotus): The Hawaiian hoary bat is a terrestrial bat species, but it is included here because it occasionally forages over water bodies. \n  It is listed as endangered due to habitat loss and disturbance. \n  Kiholo Bay and Keawaiki Bay Endemic Fishes (Various Species): Several fish species endemic to Kiholo Bay and Keawaiki Bay on the Big Island of Hawaii are listed as threatened due to habitat degradation and non-native species. \n  Hawaiian Petrel (Pterodroma sandwichensis): The Hawaiian petrel is a seabird that nests in Hawaii's high-altitude forests and forages over the ocean. \n  It is listed as threatened due to habitat loss and introduced predators. \n  Newell's Shearwater (Puffinus newelli): Similar to the Hawaiian petrel, Newell's shearwater is a seabird that nests in Hawaii and forages over the ocean. \n  It is listed as threatened due to habitat degradation and introduced predators. \n"
Idaho = "Kootenai River White Sturgeon (Acipenser transmontanus): The Kootenai River white sturgeon is a large and ancient fish species found in the Kootenai River in northern Idaho. \n  It is listed as endangered due to habitat alteration, dam construction, and altered flow regimes. \n  Bull Trout (Salvelinus confluentus): Bull trout are native to the Pacific Northwest, including Idaho. \n  They are listed as threatened in portions of their range within the state due to habitat degradation, fragmentation, and competition with non-native species. \n  Snake River Sockeye Salmon (Oncorhynchus nerka): Snake River sockeye salmon is a federally endangered species. \n  While it primarily inhabits waters in neighboring states, some Idaho rivers and streams are part of its historical range. \n  Dams, habitat alteration, and water temperature changes have contributed to its decline. \n  Chinook Salmon (Oncorhynchus tshawytscha): Several populations of Chinook salmon in Idaho are listed as threatened or endangered. \n  Dams, habitat degradation, and water diversions have been significant factors in their population declines. \n  Steelhead Trout (Oncorhynchus mykiss): Steelhead trout populations in Idaho are listed as threatened. \n  Like other salmonid species, they face threats from habitat alteration, dams, and changing environmental conditions. \n  Westslope Cutthroat Trout (Oncorhynchus clarkii lewisi): Westslope cutthroat trout are native to the western U. \n S. \n , including Idaho. \n  They are listed as threatened in some areas due to habitat loss, competition with non-native species, and hybridization. \n "
Illinois = "Higgins' Eye Pearlymussel (Lampsilis higginsii): The Higgins' eye pearlymussel is an endangered freshwater mussel species found in Illinois rivers. \n  It is listed as endangered due to habitat loss, water pollution, and changes in river flow. \n  Snuffbox Mussel (Epioblasma triquetra): The snuffbox mussel is another endangered freshwater mussel found in Illinois waters. \n  It faces similar threats to the Higgins' eye pearlymussel, including habitat degradation and water pollution. \n  Purple Cat's Paw Pearlymussel (Epioblasma obliquata obliquata): This endangered freshwater mussel species is native to Illinois rivers and is threatened by habitat loss, water pollution, and other factors. \n  Ozark Cavefish (Amblyopsis rosae): The Ozark cavefish is an endangered blind fish species found in cave systems in southern Illinois. \n  It is listed as endangered due to habitat disturbance and water quality degradation in its subterranean habitat. \n  Topeka Shiner (Notropis topeka): The Topeka shiner is a threatened minnow species found in Illinois streams. \n  It is listed as threatened due to habitat loss and degradation, including changes in stream flow and water quality. \n  Eastern Massasauga Rattlesnake (Sistrurus catenatus): While primarily a terrestrial species, the eastern massasauga rattlesnake may inhabit wetland areas in Illinois. \n  It is listed as threatened due to habitat loss and human persecution. \n "
Indiana = "Eastern Massasauga Rattlesnake (Sistrurus catenatus): While primarily a terrestrial species, the eastern massasauga rattlesnake may inhabit wetland areas in Indiana. \n  It is listed as endangered due to habitat loss and human persecution. \n  Northern Riffleshell Mussel (Epioblasma torulosa rangiana): The northern riffleshell mussel is an endangered freshwater mussel species found in Indiana rivers. \n  It is listed as endangered due to habitat loss, water pollution, and changes in river flow. \n  Slippershell Mussel (Alasmidonta viridis): The slippershell mussel is another endangered freshwater mussel species native to Indiana rivers. \n  It faces similar threats to the northern riffleshell mussel, including habitat degradation and water pollution. \n  Indiana Bat (Myotis sodalis): The Indiana bat primarily roosts in caves and mines but forages over aquatic habitats, including rivers and streams. \n  It is listed as threatened due to habitat loss and disturbance. \n  Eastern Hellbender (Cryptobranchus alleganiensis alleganiensis): The eastern hellbender is a large aquatic salamander found in Indiana's clear, fast-flowing streams. \n  It is listed as threatened due to habitat degradation, water pollution, and collection. \n  Northern Harrier (Circus hudsonius): While primarily a bird of prey, the northern harrier can be associated with wetlands and water bodies. \n  It is listed as threatened in Indiana due to habitat loss and changes in land use. \n "
Iowa = "Topeka Shiner (Notropis topeka): The Topeka shiner is a small minnow native to the central United States, including Iowa. \n  It is listed as endangered due to habitat loss and degradation, including changes in stream flow and water quality. \n  Northern Riffleshell (Epioblasma torulosa rangiana): The northern riffleshell is an endangered freshwater mussel species found in Iowa rivers. \n  It is listed as endangered due to habitat loss, water pollution, and changes in river flow. \n  Eastern Massasauga Rattlesnake (Sistrurus catenatus): While primarily a terrestrial species, the eastern massasauga rattlesnake may inhabit wetland areas in Iowa. \n  It is listed as threatened due to habitat loss and human persecution. \n  Prairie Fringed Orchid (Platanthera leucophaea): The prairie fringed orchid is a threatened plant species that can be found in wetlands and prairie habitats in Iowa. \n  It is listed as threatened due to habitat loss and degradation. \n "
Kansas = "Neosho Madtom (Noturus placidus): The Neosho madtom is an endangered small catfish species found in Kansas rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and channelization of rivers. \n  Pallid Sturgeon (Scaphirhynchus albus): While primarily associated with the Missouri River, which forms part of Kansas' northeastern border, the pallid sturgeon is considered threatened. \n  Dams, channelization, and habitat alteration are significant threats to this species. \n  Western Silvery Minnow (Hybognathus argyritis): The western silvery minnow is a threatened fish species found in some western Kansas rivers and streams. \n  It faces threats such as habitat loss, water pollution, and altered flow regimes. \n "
Kentucky = "Fanshell Mussel (Cyprogenia stegaria): The fanshell mussel is an endangered freshwater mussel species found in Kentucky rivers. \n  It is listed as endangered due to habitat loss, water pollution, and changes in river flow. \n  Ring Pink (Obovaria retusa): The ring pink is another endangered freshwater mussel species native to Kentucky rivers. \n  It faces similar threats to the fanshell mussel, including habitat degradation and water pollution. \n  Cumberland Elktoe (Alasmidonta atropurpurea): The Cumberland elktoe is an endangered freshwater mussel found in the Cumberland River system, which includes parts of Kentucky. \n  It is listed as endangered due to habitat loss and water pollution. \n  Indiana Bat (Myotis sodalis): The Indiana bat primarily roosts in caves and mines but forages over aquatic habitats, including rivers and streams. \n  It is listed as endangered due to habitat loss and disturbance. \n  Gray Bat (Myotis grisescens): Similar to the Indiana bat, the gray bat primarily roosts in caves and mines but forages over aquatic habitats. \n  It is listed as endangered due to habitat loss and disturbance. \n  Pallid Sturgeon (Scaphirhynchus albus): While primarily associated with the Mississippi and Missouri Rivers, which form part of Kentucky's western border, the pallid sturgeon is considered threatened. \n  Dams, channelization, and habitat alteration are significant threats to this species. \n "
Louisiana = "Louisiana Black Bear (Ursus americanus luteolus): The Louisiana black bear, which includes populations in bottomland hardwood forests and swamps, is listed as threatened due to habitat loss and fragmentation. \n  Gulf Sturgeon (Acipenser oxyrinchus desotoi): Gulf sturgeon are found in Gulf of Mexico drainages in Louisiana. \n  They are listed as endangered due to habitat degradation, dams, and navigation channelization. \n  Ivory-billed Woodpecker (Campephilus principalis): While primarily a bird of forested habitats, the ivory-billed woodpecker is associated with bottomland hardwood swamps in the Mississippi Alluvial Valley. \n  It is listed as endangered due to habitat loss and is considered possibly extinct. \n  Red-cockaded Woodpecker (Picoides borealis): Red-cockaded woodpeckers inhabit pine forests in Louisiana, including those in the Kisatchie National Forest. \n  They are listed as threatened due to habitat loss and degradation. \n  Mississippi Sandhill Crane (Antigone canadensis pulla): The Mississippi sandhill crane is a bird species native to the Mississippi Sandhill Crane National Wildlife Refuge in Mississippi, but it also occasionally inhabits wetland areas in Louisiana. \n  It is listed as threatened due to habitat loss and degradation. \n "
Maine = "Shortnose Sturgeon (Acipenser brevirostrum): Shortnose sturgeon is an endangered fish species found in the rivers and estuaries of Maine. \n  It is listed as endangered due to habitat degradation, dams, and overfishing. \n  Atlantic Salmon (Salmo salar): Atlantic salmon populations in Maine are listed as endangered or threatened. \n  Habitat loss, water quality issues, and obstacles to migration have contributed to their decline. \n  Northern Riffleshell Mussel (Epioblasma torulosa rangiana): The northern riffleshell mussel is an endangered freshwater mussel species found in some Maine rivers. \n  It is listed as endangered due to habitat loss, water pollution, and changes in river flow. \n  Cumberland Elktoe (Alasmidonta atropurpurea): The Cumberland elktoe is another endangered freshwater mussel species native to Maine rivers. \n  It faces similar threats to the northern riffleshell mussel, including habitat degradation and water pollution. \n  Wood Turtle (Glyptemys insculpta): Wood turtles are primarily terrestrial but inhabit areas near rivers and streams. \n  They are listed as threatened in Maine due to habitat loss and collection. \n "
Maryland = "Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon is a large, long-lived fish species found in the Chesapeake Bay and its tributaries. \n  It is listed as endangered due to overfishing, habitat degradation, and barriers to migration. \n  Loggerhead Sea Turtle (Caretta caretta): Loggerhead sea turtles nest on Maryland's beaches and are listed as threatened. \n  They face threats such as habitat degradation, artificial lighting, and fishing bycatch. \n  Hawksbill Sea Turtle (Eretmochelys imbricata): Hawksbill sea turtles are found in Maryland's coastal waters and are listed as endangered. \n  Threats include habitat degradation, accidental capture in fishing gear, and the illegal trade in hawksbill products. \n  Green Sea Turtle (Chelonia mydas): Green sea turtles are commonly found in Maryland's coastal waters and are listed as threatened. \n  Conservation efforts have helped their populations recover, but they still face threats such as habitat degradation and bycatch. \n  Leatherback Sea Turtle (Dermochelys coriacea): Leatherback sea turtles occasionally visit Maryland waters and are listed as endangered. \n  They face threats such as bycatch in fishing gear and ingestion of marine debris. \n  Atlantic Ridgway's Rail (Rallus obsoletus): Ridgway's rail is a secretive marsh bird found in coastal wetlands. \n  It is listed as threatened in Maryland due to habitat loss and degradation. \n  Northern Long-eared Bat (Myotis septentrionalis): While primarily a terrestrial species, the northern long-eared bat is included here because it relies on aquatic habitats for drinking. \n  It is listed as threatened due to the threat of white-nose syndrome, habitat loss, and disturbance. \n "
Massachusetts = "Shortnose Sturgeon (Acipenser brevirostrum): Shortnose sturgeon is an endangered fish species found in the rivers and estuaries of Massachusetts. \n  It is listed as endangered due to habitat degradation, dams, and overfishing. \n  Atlantic Salmon (Salmo salar): Atlantic salmon populations in Massachusetts are listed as endangered. \n  Habitat loss, water quality issues, and obstacles to migration have contributed to their decline. \n  Northern Red-bellied Cooter (Pseudemys rubriventris): The northern red-bellied cooter is an endangered turtle species found in some Massachusetts ponds and wetlands. \n  It is listed as endangered due to habitat loss and degradation. \n  Eastern Box Turtle (Terrapene carolina carolina): While primarily a terrestrial species, the eastern box turtle is included here because it often inhabits wetland areas. \n  It is listed as threatened due to habitat loss and road mortality. \n  Eastern Spadefoot Toad (Scaphiopus holbrookii): The eastern spadefoot toad is a threatened amphibian species found in sandplain habitats, including some in Massachusetts. \n  It is listed as threatened due to habitat loss and alteration. \n "
Michigan = "Piping Plover (Charadrius melodus): While primarily a bird species, the piping plover nests on Great Lakes beaches and is listed as endangered in Michigan due to habitat loss and disturbance. \n  Eastern Massasauga Rattlesnake (Sistrurus catenatus): The eastern massasauga rattlesnake may inhabit wetland areas in Michigan. \n  It is listed as endangered due to habitat loss and human persecution. \n  Lakeside Daisy (Tetraneuris herbacea): The lakeside daisy is an endangered plant species found in Great Lakes dune habitats in Michigan. \n  It is listed as endangered due to habitat loss and degradation. \n  Piping Plover (Charadrius melodus): The piping plover is a small shorebird that nests on Great Lakes beaches in Michigan. \n  It is listed as endangered due to habitat loss, disturbance, and predation. \n  Hine's Emerald Dragonfly (Somatochlora hineana): While primarily a terrestrial insect, the Hine's emerald dragonfly may inhabit wetlands in Michigan. \n  It is listed as endangered due to habitat loss and water quality degradation. \n  Eastern Massasauga Rattlesnake (Sistrurus catenatus): The eastern massasauga rattlesnake may inhabit wetland areas in Michigan. \n  It is listed as threatened due to habitat loss and human persecution. \n  Peregrine Falcon (Falco peregrinus): Peregrine falcons may nest on cliffs along the Great Lakes, and they are listed as threatened due to habitat loss and pesticide exposure. \n "
Minnesota = "Topeka Shiner (Notropis topeka): The Topeka shiner is a small minnow species found in Minnesota's prairie streams. \n  It is listed as endangered due to habitat loss, including changes in stream flow and water quality. \n  Spectaclecase Mussel (Cumberlandia monodonta): The spectaclecase mussel is an endangered freshwater mussel species found in some Minnesota rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Higgins' Eye Pearlymussel (Lampsilis higginsii): The Higgins' eye pearlymussel is another endangered freshwater mussel found in Minnesota rivers. \n  It faces similar threats to the spectaclecase mussel, including habitat degradation and water pollution. \n  Minnesota Loggerhead Shrike (Lanius ludovicianus excubitorides): The loggerhead shrike is primarily a terrestrial bird species, but it may inhabit wetland areas in Minnesota. \n  It is listed as endangered due to habitat loss and changes in land use. \n  Blanding's Turtle (Emydoidea blandingii): Blanding's turtles are semi-aquatic and can be found in wetland areas in Minnesota. \n  They are listed as threatened due to habitat loss and road mortality. \n  Northern Riffleshell Mussel (Epioblasma torulosa rangiana): The northern riffleshell mussel is a threatened freshwater mussel species found in some Minnesota rivers. \n  It is listed as threatened due to habitat degradation, water pollution, and changes in river flow. \n "
Mississippi = "Ringed Map Turtle (Graptemys oculifera): The ringed map turtle is an endangered turtle species found in Mississippi's rivers and streams. \n  It is listed as endangered due to habitat loss, water pollution, and collection for the pet trade. \n  Yellow Blotched Map Turtle (Graptemys flavimaculata): The yellow blotched map turtle is another endangered turtle species native to Mississippi rivers and streams. \n  Like the ringed map turtle, it faces threats such as habitat loss, water pollution, and collection. \n  Alabama Pearlshell Mussel (Margaritifera marrianae): The Alabama pearlshell mussel is an endangered freshwater mussel species found in Mississippi rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Gulf Sturgeon (Acipenser oxyrinchus desotoi): Gulf sturgeon are found in Gulf of Mexico drainages in Mississippi. \n  They are listed as endangered due to habitat degradation, dams, and navigation channelization. \n  Southern Clubshell Mussel (Pleurobema decisum): The southern clubshell mussel is an endangered freshwater mussel species found in some Mississippi rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Choctawhatchee River Drainage Fishes (Various Species): Several fish species native to the Choctawhatchee River drainage in Mississippi are listed as endangered due to habitat degradation and competition with non-native species. \n "
Missouri = "Ozark Hellbender (Cryptobranchus alleganiensis bishopi): The Ozark hellbender is an endangered aquatic salamander species found in Missouri's clear, fast-flowing streams. \n  It is listed as endangered due to habitat degradation, water pollution, and disease. \n  Pallid Sturgeon (Scaphirhynchus albus): While primarily associated with the Missouri River, which forms part of Missouri's borders, the pallid sturgeon is considered endangered. \n  Dams, channelization, and habitat alteration are significant threats to this species. \n  Niangua Darter (Etheostoma nianguae): The Niangua darter is an endangered fish species found in a few Ozark streams in Missouri. \n  It is listed as endangered due to habitat degradation and competition with non-native species. \n  Hine's Emerald Dragonfly (Somatochlora hineana): While primarily a terrestrial insect, the Hine's emerald dragonfly may inhabit wetlands in Missouri. \n  It is listed as endangered due to habitat loss and water quality degradation. \n  Topeka Shiner (Notropis topeka): The Topeka shiner is a small minnow species found in Missouri's prairie streams. \n  It is listed as threatened due to habitat loss, including changes in stream flow and water quality. \n  Eastern Massasauga Rattlesnake (Sistrurus catenatus): The eastern massasauga rattlesnake may inhabit wetland areas in Missouri. \n  It is listed as threatened due to habitat loss and human persecution. \n  Neosho Madtom (Noturus placidus): The Neosho madtom is a threatened small catfish species found in Missouri rivers and streams. \n  It faces threats such as habitat loss and water pollution. \n "
Montana = "Bull Trout (Salvelinus confluentus): Bull trout are native to Montana and are listed as a threatened species. \n  They face habitat degradation, overfishing, and competition with non-native species. \n  Westslope Cutthroat Trout (Oncorhynchus clarkii lewisi): Westslope cutthroat trout are native to Montana and are listed as a threatened species. \n  Habitat loss, fragmentation, and competition with non-native trout species are major threats. \n  Sturgeon Chub (Macrhybopsis gelida): The sturgeon chub is an endangered fish species found in some Montana rivers. \n  It is listed as endangered due to habitat degradation and fragmentation. \n Northern Leopard Frog (Lithobates pipiens): Northern leopard frogs are semi-aquatic amphibians found in wetland habitats in Montana. \n  They are listed as threatened due to habitat loss, disease, and pesticide exposure. \n  Topeka Shiner (Notropis topeka): The Topeka shiner is a small minnow species found in Montana's prairie streams. \n  It is listed as threatened due to habitat loss, including changes in stream flow and water quality. \n "
Nebraska = "Pallid Sturgeon (Scaphirhynchus albus): Pallid sturgeon is a critically endangered fish species found in the Missouri River system, which forms part of Nebraska's borders. \n  Dams, channelization, and habitat alteration are significant threats to this species. \n  Topeka Shiner (Notropis topeka): The Topeka shiner is a small minnow species found in Nebraska's prairie streams. \n  It is listed as endangered due to habitat loss, including changes in stream flow and water quality. \n  Northern Long-eared Bat (Myotis septentrionalis): While primarily a terrestrial species, the northern long-eared bat is included here because it often drinks from aquatic habitats. \n  It is listed as threatened due to the threat of white-nose syndrome, habitat loss, and disturbance. \n "
Nevada = "Devil's Hole Pupfish (Cyprinodon diabolis): Devil's Hole pupfish are critically endangered and found only in Devil's Hole, a unique geothermal pool in Death Valley National Park that extends into Nevada. \n  They are highly specialized and face threats related to habitat degradation and water level fluctuations. \n  Ash Meadows Speckled Dace (Rhinichthys osculus nevadesis): The Ash Meadows speckled dace is a threatened fish species found in several spring-fed pools and streams in the Ash Meadows National Wildlife Refuge in Nevada. \n  It is threatened due to habitat degradation and non-native species introductions. \n  Meadow Valley Wash Speckled Dace (Rhinichthys osculus thermalis): This speckled dace subspecies is found in Meadow Valley Wash in eastern Nevada and is listed as threatened. \n  It faces similar threats to the Ash Meadows speckled dace, including habitat degradation and competition with non-native species. \n "
New_Hampshire = "Piping Plover (Charadrius melodus): While primarily a bird species, the piping plover nests on New Hampshire's beaches and is listed as endangered in the state due to habitat loss and disturbance. \n  Shortnose Sturgeon (Acipenser brevirostrum): Shortnose sturgeon are found in New Hampshire's rivers and estuaries. \n  They are listed as endangered due to habitat degradation, dams, and overfishing. \n  Bald Eagle (Haliaeetus leucocephalus): Bald eagles often inhabit lakes and rivers in New Hampshire. \n  They are listed as threatened due to habitat loss, disturbance, and pesticide exposure. \n  Eastern Box Turtle (Terrapene carolina carolina): While primarily a terrestrial species, the eastern box turtle often inhabits wetland areas. \n  It is listed as threatened due to habitat loss and road mortality. \n "
New_Jersey = "Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon are found in New Jersey's coastal and estuarine waters, particularly in the Delaware River. \n  They are listed as endangered due to habitat degradation, overfishing, and barriers to migration. \n  Red Knot (Calidris canutus): While primarily a bird species, the red knot relies on coastal habitats, including beaches and estuaries, in New Jersey during migration. \n  It is listed as endangered due to habitat loss and disturbance. \n  Piping Plover (Charadrius melodus): Piping plovers nest on New Jersey's coastal beaches and are listed as endangered due to habitat loss and disturbance. \n  Indiana Bat (Myotis sodalis): Indiana bats forage over aquatic habitats, including rivers and streams. \n  They are listed as endangered due to habitat loss and disturbance. \n  Northern Long-eared Bat (Myotis septentrionalis): While primarily a terrestrial species, the northern long-eared bat often drinks from aquatic habitats. \n  It is listed as threatened due to the threat of white-nose syndrome, habitat loss, and disturbance. \n "
New_Mexico = "Gila Trout (Oncorhynchus gilae): The Gila trout is a native trout species found in New Mexico's Gila River Basin and surrounding areas. \n  It is listed as endangered due to habitat degradation and competition with non-native trout species. \n  Rio Grande Silvery Minnow (Hybognathus amarus): The Rio Grande silvery minnow is a small fish species found in the Rio Grande River system in New Mexico. \n  It is listed as endangered due to habitat alteration, water management practices, and competition with non-native species. \n  Southwestern Willow Flycatcher (Empidonax traillii extimus): While primarily a bird species, the Southwestern willow flycatcher depends on riparian habitats, which often include aquatic areas. \n  It is listed as endangered due to habitat loss and degradation. \n  Razorback Sucker (Xyrauchen texanus): The razorback sucker is a fish species found in the Colorado River Basin in New Mexico. \n  It is listed as threatened due to habitat alteration, water management practices, and competition with non-native species. \n  Yellow-billed Cuckoo (Coccyzus americanus): Yellow-billed cuckoos are primarily bird species associated with riparian habitats, including aquatic areas. \n  They are listed as threatened due to habitat loss and degradation. \n "
New_York = "Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon are found in New York's coastal and estuarine waters, including the Hudson River. \n  They are listed as endangered due to habitat degradation, overfishing, and barriers to migration. \n  Shortnose Sturgeon (Acipenser brevirostrum): Shortnose sturgeon are found in New York's rivers and estuaries, particularly in the Hudson River. \n  They are listed as endangered due to habitat degradation, dams, and overfishing. \n  Piping Plover (Charadrius melodus): Piping plovers nest on New York's coastal beaches and are listed as endangered due to habitat loss and disturbance. \n  Kemp's Ridley Sea Turtle (Lepidochelys kempii): While primarily a marine species, Kemp's Ridley sea turtles can be found in New York's coastal waters. \n  They are listed as endangered due to habitat degradation, accidental capture in fishing gear, and pollution. \n  Wood Turtle (Glyptemys insculpta): Wood turtles are primarily terrestrial but often inhabit areas near rivers and streams. \n  They are listed as threatened due to habitat loss and collection. \n  Eastern Spadefoot Toad (Scaphiopus holbrookii): The eastern spadefoot toad is a threatened amphibian species found in sandplain habitats, including some in New York. \n  It is listed as threatened due to habitat loss and alteration. \n "
North_Carolina = "Carolina Heelsplitter (Lasmigona decorata): The Carolina heelsplitter is an endangered freshwater mussel species found in some North Carolina rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  James Spinymussel (Pleurobema collina): The James spinymussel is another endangered freshwater mussel species native to some North Carolina rivers. \n  It faces similar threats to the Carolina heelsplitter, including habitat degradation and water pollution. \n  Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon are found in North Carolina's coastal and estuarine waters. \n  They are listed as endangered due to habitat degradation, overfishing, and barriers to migration. \n  Shortnose Sturgeon (Acipenser brevirostrum): Shortnose sturgeon are found in North Carolina's rivers and estuaries. \n  They are listed as endangered due to habitat degradation, dams, and overfishing. \n  Loggerhead Sea Turtle (Caretta caretta): Loggerhead sea turtles nest on North Carolina's beaches and are listed as threatened. \n  They face threats such as habitat degradation, artificial lighting, and fishing bycatch. \n  Red-Cockaded Woodpecker (Leuconotopicus borealis): While primarily a terrestrial bird species, the red-cockaded woodpecker often forages in wetlands and riparian areas. \n  It is listed as threatened due to habitat loss and alteration. \n  American Alligator (Alligator mississippiensis): American alligators inhabit wetland areas in North Carolina. \n  They are listed as threatened due to habitat loss and overhunting. \n "
North_Dakota = "North Dakota is a primarily landlocked state with limited aquatic habitats compared to some other states. There are no government recognized endangered aquatic species."
Ohio = "Higgins' Eye Pearlymussel (Lampsilis higginsii): The Higgins' eye pearlymussel is an endangered freshwater mussel species found in some Ohio rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Northern Riffleshell (Epioblasma torulosa rangiana): The northern riffleshell is another endangered freshwater mussel species native to some Ohio rivers. \n  It faces similar threats to the Higgins' eye pearlymussel, including habitat degradation and water pollution. \n  Clubshell Mussel (Pleurobema clava): The clubshell mussel is an endangered species found in some Ohio rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Fanshell (Cyprogenia stegaria): The fanshell is an endangered freshwater mussel found in some Ohio rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Eastern Massasauga Rattlesnake (Sistrurus catenatus): While primarily a terrestrial species, the eastern massasauga rattlesnake often inhabits wetland areas in Ohio. \n  It is listed as endangered due to habitat loss and human persecution. \n  Paddlefish (Polyodon spathula): Paddlefish are listed as threatened in Ohio due to habitat degradation and overharvest. \n "
Oklahoma = "Interior Least Tern (Sternula antillarum athalassos): While primarily a bird species, the interior least tern nests on sandbars along rivers in Oklahoma. \n  It is listed as endangered due to habitat loss and disturbance. \n  Arkansas River Shiner (Notropis girardi): The Arkansas River shiner is an endangered minnow species found in some Oklahoma rivers. \n  It is listed as endangered due to habitat degradation and water pollution. \n  Paddlefish (Polyodon spathula): Paddlefish are listed as endangered in Oklahoma due to habitat degradation and overharvest. \n  Neosho Madtom (Noturus placidus): The Neosho madtom is a threatened small catfish species found in some Oklahoma rivers and streams. \n  It faces threats such as habitat loss and water pollution. \n "
Oregon = "Oregon Spotted Frog (Rana pretiosa): While primarily a terrestrial amphibian, the Oregon spotted frog depends on wetland habitats. \n  It is listed as endangered due to habitat loss and alteration. \n  Shortnose Sucker (Chasmistes brevirostris): Shortnose suckers are found in some Oregon rivers and lakes. \n  They are listed as endangered due to habitat degradation, dams, and competition with non-native species. \n  Lost River Sucker (Deltistes luxatus): Lost River suckers are found in some Oregon lakes and rivers. \n  They are listed as endangered due to habitat degradation, dams, and competition with non-native species. \n  Klamath Small-Scale Sucker (Catostomus rimiculus): The Klamath small-scale sucker is another endangered fish species found in some Oregon lakes and rivers. \n  It faces similar threats to the Lost River sucker, including habitat degradation and competition with non-native species. \n  Steelhead Trout (Oncorhynchus mykiss irideus): While steelhead trout are a diverse group of anadromous trout, some populations are listed as endangered in Oregon due to habitat degradation, dams, and overfishing. \n  Bull Trout (Salvelinus confluentus): Bull trout are native to Oregon's coldwater streams and lakes. \n  They are listed as threatened due to habitat degradation, overfishing, and competition with non-native species. \n "
Pennsylvania = "Eastern Sand Darter (Ammocrypta pellucida): The eastern sand darter is an endangered small fish species found in some Pennsylvania rivers and streams. \n  It is listed as endangered due to habitat degradation and water pollution. \n  Snuffbox Mussel (Epioblasma triquetra): The snuffbox mussel is an endangered freshwater mussel species native to some Pennsylvania rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Spotted Turtle (Clemmys guttata): While primarily a terrestrial turtle species, spotted turtles often inhabit wetland areas. \n  They are listed as threatened due to habitat loss and collection. \n  Wood Turtle (Glyptemys insculpta): Wood turtles are primarily terrestrial but often inhabit areas near rivers and streams. \n  They are listed as threatened due to habitat loss and collection. \n "
Rhode_Island = "Rhode Island is a small state with limited aquatic habitats, and it may not have as many federally listed aquatic species as larger states. \n  There are no government recognized endangered aquatic species. \n "
South_Carolina = "Shortnose Sturgeon (Acipenser brevirostrum): Shortnose sturgeon are found in some South Carolina rivers and estuaries. \n  They are listed as endangered due to habitat degradation, dams, and overfishing. \n  Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon are found in South Carolina's coastal and estuarine waters. \n  They are listed as endangered due to habitat degradation, overfishing, and barriers to migration. \n  Red-Cockaded Woodpecker (Leuconotopicus borealis): While primarily a terrestrial bird species, the red-cockaded woodpecker often forages in wetlands and riparian areas. \n  It is listed as endangered due to habitat loss and alteration. \n  Wood Stork (Mycteria americana): Wood storks are wading birds that often forage in aquatic habitats, including freshwater and brackish wetlands. \n  They are listed as endangered due to habitat loss and disturbance. \n  Loggerhead Sea Turtle (Caretta caretta): Loggerhead sea turtles nest on South Carolina's beaches and are listed as threatened. \n  They face threats such as habitat loss, artificial lighting, and fishing bycatch. \n  Kemp's Ridley Sea Turtle (Lepidochelys kempii): While primarily a marine species, Kemp's Ridley sea turtles can be found in South Carolina's coastal waters. \n  They are listed as endangered due to habitat degradation, accidental capture in fishing gear, and pollution. \n "
South_Dakota = "South Dakota is a landlocked state with limited aquatic habitats compared to some other states, and it may not have as many federally listed aquatic species. \n There are no government recognized endangered aquatic species. \n"
Tennessee = "Barrens Topminnow (Fundulus julisia): The Barrens topminnow is an endangered fish species native to some Tennessee streams and springs. \n  It is listed as endangered due to habitat degradation and competition with non-native species. \n  Laurel Dace (Chrosomus saylori): The laurel dace is another endangered minnow species found in some Tennessee streams. \n  It is listed as endangered due to habitat degradation and competition with non-native species. \n  Duskytail Darter (Etheostoma percnurum): The duskytail darter is an endangered fish species found in some Tennessee rivers and streams. \n  It is listed as endangered due to habitat degradation and competition with non-native species. \n  Fountain Darter (Etheostoma fonticola): The fountain darter is a threatened fish species found in some Tennessee streams. \n  It is listed as threatened due to habitat degradation and competition with non-native species. \n  Southern Clubshell Mussel (Pleurobema decisum): The southern clubshell mussel is a threatened freshwater mussel species found in some Tennessee rivers. \n  It is listed as threatened due to habitat degradation and water pollution. \n "
Texas = "Whooping Crane (Grus americana): While primarily a bird species, the whooping crane often inhabits wetland areas along the Texas Gulf Coast. \n  It is listed as endangered due to habitat loss and disturbance. \n  Texas Wild-rice (Zizania texana): Texas wild-rice is an endangered aquatic plant species found in the San Marcos River and the Comal Springs in Texas. \n  It is listed as endangered due to habitat degradation and competition with non-native plants. \n  Texas Blind Salamander (Eurycea rathbuni): The Texas blind salamander is an endangered amphibian species found in some Texas aquifers and caves. \n  It is listed as endangered due to habitat degradation, pollution, and changes in water quality. \n  Comal Springs Riffle Beetle (Heterelmis comalensis): The Comal Springs riffle beetle is an endangered aquatic beetle species found in the Comal Springs in Texas. \n  It is listed as endangered due to habitat degradation and changes in water quality. \n  San Marcos Gambusia (Gambusia georgei): The San Marcos gambusia is an endangered fish species native to the San Marcos Springs in Texas. \n  It is listed as endangered due to habitat degradation and competition with non-native species. \n  American Alligator (Alligator mississippiensis): American alligators inhabit wetland areas in Texas. \n  They are listed as threatened due to habitat loss and overhunting. \n  Green Sea Turtle (Chelonia mydas): Green sea turtles can be found in the coastal waters of Texas and are listed as threatened. \n  They face threats such as habitat degradation, boat strikes, and fishing bycatch. \n "
Utah = "Virgin River Chub (Gila seminuda): The Virgin River chub is an endangered fish species native to the Virgin River system in Utah. \n  It is listed as endangered due to habitat degradation, water pollution, and competition with non-native species. \n  Virgin Spinedace (Lepidomeda mollispinis mollispinis): The Virgin spinedace is another endangered fish species found in the Virgin River system. \n  It is listed as endangered due to habitat degradation, water pollution, and competition with non-native species. \n  Bonneville Cutthroat Trout (Oncorhynchus clarkii utah): The Bonneville cutthroat trout is the state fish of Utah and is listed as threatened due to habitat degradation, competition with non-native trout species, and hybridization. \n  Colorado Pikeminnow (Ptychocheilus lucius): The Colorado pikeminnow is a large fish species found in some Utah rivers. \n  It is listed as threatened due to habitat alteration, dams, and water management practices. \n  Razorback Sucker (Xyrauchen texanus): Razorback suckers are found in the Colorado River Basin in Utah. \n  They are listed as threatened due to habitat alteration, dams, and competition with non-native species. \n " 
Vermont = "Spiny Softshell Turtle (Apalone spinifera): While primarily a terrestrial turtle species, the spiny softshell turtle often inhabits aquatic habitats, including rivers and lakes in Vermont. \n  It is listed as endangered due to habitat loss, degradation, and human disturbance. \n  Rayed Bean (Villosa fabalis): The rayed bean is an endangered freshwater mussel species found in some Vermont rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Eastern Spiny Softshell Turtle (Apalone spinifera): Similar to the spiny softshell turtle, the eastern spiny softshell turtle is also found in aquatic habitats in Vermont. \n  It is listed as threatened due to habitat loss and disturbance. \n  Brook Floater (Alasmidonta varicosa): The brook floater is a threatened freshwater mussel species found in some Vermont rivers. \n  It is listed as threatened due to habitat degradation, water pollution, and changes in river flow. \n  Brook Floater (Alasmidonta varicosa): The brook floater is a threatened freshwater mussel species found in some Vermont rivers. \n  It is listed as threatened due to habitat degradation, water pollution, and changes in river flow. \n "
Virginia = "James Spinymussel (Pleurobema collina): The James spinymussel is an endangered freshwater mussel species native to some Virginia rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Roanoke Logperch (Percina rex): The Roanoke logperch is an endangered fish species found in some Virginia rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and competition with non-native species. \n  Tar River Spiny Mussel (Elliptio steinstansana): The Tar River spiny mussel is an endangered freshwater mussel species found in some Virginia rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Sturgeon Chub (Macrhybopsis gelida): The sturgeon chub is an endangered minnow species found in some Virginia rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and competition with non-native species. \n  Atlantic Sturgeon (Acipenser oxyrinchus oxyrinchus): Atlantic sturgeon are found in Virginia's coastal and estuarine waters. \n  They are listed as threatened due to habitat degradation, overfishing, and barriers to migration. \n  Eastern Spadefoot Toad (Scaphiopus holbrookii): The eastern spadefoot toad is a threatened amphibian species found in sandplain habitats, including some in Virginia. \n  It is listed as threatened due to habitat loss and alteration. \n "
Washington = "Lower Columbia River Chinook Salmon (Oncorhynchus tshawytscha): Chinook salmon populations in the lower Columbia River are listed as endangered. \n  They face various threats, including habitat degradation, dams, and changes in river flow. \n  Upper Columbia River Spring Chinook Salmon (Oncorhynchus tshawytscha): Spring Chinook salmon in the upper Columbia River are listed as endangered due to similar threats as the lower Columbia River Chinook salmon. \n  Snake River Fall Chinook Salmon (Oncorhynchus tshawytscha): Fall Chinook salmon in the Snake River are listed as endangered. \n  They are impacted by dams, habitat degradation, and changes in river flow. \n  Snake River Sockeye Salmon (Oncorhynchus nerka): Sockeye salmon in the Snake River are listed as endangered. \n  They face threats such as dams, habitat degradation, and changes in river flow. \n  Puget Sound Steelhead Trout (Oncorhynchus mykiss): Steelhead trout populations in Puget Sound are listed as endangered. \n  They face various threats, including habitat degradation and competition with non-native species. \n  Lower Columbia River Coho Salmon (Oncorhynchus kisutch): Coho salmon populations in the lower Columbia River are listed as threatened. \n  They are impacted by habitat degradation, dams, and changes in river flow. \n  Upper Columbia River Steelhead Trout (Oncorhynchus mykiss): Steelhead trout in the upper Columbia River are listed as threatened due to similar threats as the upper Columbia River spring Chinook salmon. \n  Bull Trout (Salvelinus confluentus): Bull trout populations in various regions of Washington are listed as threatened. \n  They are impacted by habitat degradation, overfishing, and competition with non-native species. \n  Western Pond Turtle (Actinemys marmorata): While primarily a terrestrial turtle species, the western pond turtle often inhabits aquatic habitats, including ponds and wetlands in Washington. \n  It is listed as threatened due to habitat loss and degradation. \n "
West_Virginia = "Diamond Darter (Crystallaria cincotta): The diamond darter is an endangered fish species found in the Elk River drainage in West Virginia. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Olive Darter (Percina squamata): The olive darter is another endangered fish species native to some West Virginia rivers and streams. \n  It is listed as endangered due to habitat degradation and competition with non-native species. \n  Eastern Hellbender (Cryptobranchus alleganiensis alleganiensis): The eastern hellbender is a threatened salamander species found in some West Virginia rivers and streams. \n  It is listed as threatened due to habitat degradation, water pollution, and changes in water quality. \n "
Wisconsin = "Piping Plover (Charadrius melodus): While primarily a shorebird species, the piping plover often nests on sandy beaches along Lake Michigan and Lake Superior in Wisconsin. \n  It is listed as endangered due to habitat loss and disturbance. \n  Higgins' Eye Pearlymussel (Lampsilis higginsii): The Higgins' eye pearlymussel is an endangered freshwater mussel species found in some Wisconsin rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Spectaclecase (Cumberlandia monodonta): The spectaclecase is another endangered freshwater mussel species native to some Wisconsin rivers. \n  It is listed as endangered due to habitat degradation, water pollution, and changes in river flow. \n  Northern Riffleshell (Epioblasma torulosa rangiana): The northern riffleshell is a threatened freshwater mussel species found in some Wisconsin rivers. \n  It is listed as threatened due to habitat degradation, water pollution, and changes in river flow. \n  Eastern Massasauga Rattlesnake (Sistrurus catenatus): The eastern massasauga rattlesnake is a threatened reptile species found in wetland areas, including some in Wisconsin. \n  It is listed as threatened due to habitat loss and collection. \n"
Wyoming = "Black-footed Ferret (Mustela nigripes): While primarily a terrestrial mammal, the black-footed ferret sometimes inhabits riparian areas and may be found near water sources. \n  It is listed as endangered due to habitat loss and disease. \n  Westslope Cutthroat Trout (Oncorhynchus clarkii lewisi): Westslope cutthroat trout populations in some Wyoming streams and rivers are listed as threatened. \n  They face threats such as habitat degradation, competition with non-native species, and hybridization. \n"

class FrontScreen(Screen):
    def __init__(self, **kwargs):
        self.image = Image(source='logo2.png')
        super().__init__(**kwargs)
        self.layout = BoxLayout(orientation='vertical')
        self.label = Label(text="Enter a state:")
        self.message_input = TextInput()
        self.submit_button = Button(text="Submit", on_press=self.submit_message)
        self.layout.add_widget(self.label)
        self.layout.add_widget(self.image)
        self.layout.add_widget(self.message_input)
        self.layout.add_widget(self.submit_button)
        self.add_widget(self.layout)

    def submit_message(self, instance):
        message = self.message_input.text
        app = App.get_running_app()
        app.message = message  
        app.root.current = 'second'  
        my_user_input = TextInput(multiline=True)


class StateInput(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.layout = BoxLayout(orientation='vertical')
        self.label = Label(text="Endangered animals from state: ")
        self.message_label = Label()
        self.layout.add_widget(self.label)
        self.layout.add_widget(self.message_label)
        self.add_widget(self.layout)
        

    def on_pre_enter(self):
        app = App.get_running_app()
        message = ""
        if app.message == "Alabama":
	        message = Alabama

        if app.message == "Alaska":
            message = Alaska

        if app.message == "Arizona":
            message = Arizona

        if app.message == "Arkansas":
            message = Arkansas

        if app.message == "California":
            message = California

        if app.message == "Colorado":
            message = Colorado

        if app.message == "Connecticut":
            message = Connecticut

        if app.message == "Delaware":
            message = Delaware

        if app.message == "Florida":
            message = Florida

        if app.message == "Georgia":
            message = Georgia

        if app.message == "Hawaii":
            message = Hawaii

        if app.message == "Idaho":
            message = Idaho

        if app.message == "Illinois":
            message = Illinois

        if app.message == "Indiana":
            message = Indiana

        if app.message == "Iowa":
            message = Iowa

        if app.message == "Kansas":
            message = Kansas

        if app.message == "Kentucky":
            message = Kentucky

        if app.message == "Louisiana":
            message = Louisiana

        if app.message == "Maine":
            message = Maine

        if app.message == "Maryland":
            message = Maryland

        if app.message == "Massachusetts":
            message = Massachusetts

        if app.message == "Michigan":
            message = Michigan

        if app.message == "Minnesota":
            message =  Minnesota

        if app.message == "Mississippi":
            message = Mississippi

        if app.message == "Missouri":
            message = Missouri

        if app.message == "Montana":
            message = Montana

        if app.message == "Nebraska":
            message = Nebraska

        if app.message == "Nevada":
            message = Nevada

        if app.message == "New Hampshire":
            message = New_Hampshire

        if app.message == "New Jersey":
            message = New_Jersey

        if app.message == "New Mexico":
            message = New_Mexico

        if app.message == "New York":
            message = New_York

        if app.message == "North Carolina":
            message = North_Carolina

        if app.message == "North Dakota":
            message = North_Dakota

        if app.message == "Ohio":
            message = Ohio

        if app.message == "Oklahoma":
            message = Oklahoma

        if app.message == "Oregon":
            message = Oregon

        if app.message == "Pennsylvania":
            message = Pennsylvania

        if app.message == "Rhode Island":
            message = Rhode_Island

        if app.message == "South Carolina":
            message = South_Carolina

        if app.message == "South Dakota":
            message = South_Dakota

        if app.message == "Tennessee":
            message = Tennessee

        if app.message == "Texas":
            message = Texas

        if app.message == "Utah":
            message = Utah

        if app.message == "Vermont":
            message = Vermont

        if app.message == "Virginia":
            message = Virginia

        if app.message == "Washington":
            message = Washington

        if app.message == "West Virginia":
            message = West_Virginia

        if app.message == "Wisconsin":
            message = Wisconsin

        if app.message == "Wyoming":
            message = Wyoming
        
  
        self.message_label.text = message

class MyApp(App):
    def build(self):
        self.window = FrontScreen()
        self.window.cols = 4
        self.window.size_hint = (0.6, 0.7)
        self.window.pos_hint = {"center_x": 0.5, "center_y":0.5}


        self.window.add_widget(Image(source="logo2.png"))

        self.message = ""  
        self.screen_manager = ScreenManager()
        self.first_screen = FrontScreen(name='first')
        self.second_screen = StateInput(name='second')
        self.screen_manager.add_widget(self.first_screen)
        self.screen_manager.add_widget(self.second_screen)
        return self.screen_manager

if __name__ == '__main__':
    MyApp().run()